# Generated by Django 2.2.1 on 2021-05-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True)),
                ('created', models.DateField(default='2021-05-28')),
                ('due_date', models.DateField(default='2021-05-28')),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
